### ISSUE TITLE
Update binding section

### ISSUE THREAD

**Issue by mjjaniec** [UdashFramework/udash-guide#31]
http://guide.udash.io/#/frontend/bindings chapter is advising to use `bindValidation` and `bindAttribute` which are both deprecated. Please update the doc

**Comment by mjjaniec** [comment]
more about properties. What is the purpose of `CastableProperty`?  What is `DirectSeqProperty`, its used in example code, but is not described. 
Please add a notice that model's `get` called two times in a row could return two different instances

**Comment by Starzu** [comment]
@mjjaniec `bindValidation` and `bindAttribute` are deprecated since `0.4`. It will be updated after `0.4` release.

**Comment by Starzu** [comment]
Done in #32
