### ISSUE TITLE
SBT bootstrapping doesn't compile without copyStatics

### ISSUE THREAD

**Issue by jlncrnt** [UdashFramework/udash-guide#36]
Hi, 

thank you for your work on Udash. It seems to be a fantastic framework and I would like to use it to implement a GUI for a bioinformatics project.

I followed the bootstrapping tutorial [here](http://guide.udash.io/#/bootstrapping/sbt) but I've been able to run SBT without error only by adding `import org.scalajs.sbtplugin.ScalaJSPlugin.AutoImport._` in the beginning of the `project/Dependencies` file and `import Dependencies._` in my root `build.sbt` file. I also had to use the `%%%!` macro instead of `%%%` for the `crossDeps` and `frontendDeps` values.

I'm using sbt 0.13.15 and IntelliJ. Is it a problem with SBT, Udash or am I missing something ?

Thank you !

jlncrnt

**Comment by Starzu** [comment]
Hi @jlncrnt!

Thank you for this bug report. Project bootstrapping guide is quite old and probably not up to date with SBT changes. 

For now you can try to use [Udash project generator](http://guide.udash.io/#/bootstrapping/generators) or take a look at configuration of this project.

**Comment by Starzu** [comment]
The new project bootstrapping tutorial: https://guide.udash.io/#/bootstrapping
